...@AWSCompute
...@AWSApplicationIntegration
...@AWSContainers
...@AWSDatabase
...@AWSNetworking
...@AWSSecurityIdentity
...@AWSStorage

classes {
  Firewall: {
      icon: https://icons.terrastruct.com/aws%2FNetworking%20&%20Content%20Delivery%2FAmazon-Route-53_Hosted-Zone_light-bg.svg
  }
  Blue: {
      style: {
          stroke: '#003366'
          font-color: '#003366'
          fill: '#99ccff'
          border-radius: 5
      }
  }
  Purple: {
      style: {
          stroke: '#5c4171'
          font-color: '#5c4171'
          fill: '#d0b0e8'
          border-radius: 5
      }
  }
  White: {
      style: {
          stroke: '#3e3b38'
          font-color: '#3e3b38'
          fill: transparent
          border-radius: 5
      }
  }
  Empty: {
      style: {
          stroke: transparent
          font-color: black
          fill: transparent
      }
  }
}
