classes: {
    AWSStorage-S3: {
        icon: https://icons.terrastruct.com/aws%2FStorage%2FAmazon-Simple-Storage-Service-S3.svg     
        shape: image
        width: 100
        height: 100
    }
}