classes: {  
    Miscellaneous-Docker: {
        icon: https://icons.terrastruct.com/dev%2Fdocker.svg
        shape: image
        width: 100
        height: 100
    }
    Miscellaneous-Github: {
        icon: https://icons.terrastruct.com/dev%2Fgithub.svg
        shape: image
        width: 100
        height: 100
    }
    Miscellaneous-User: {
        icon: 'https://icons.terrastruct.com/essentials%2F365-user.svg'
        shape: image
        width: 100
        height: 100
    }
    Miscellaneous-Developer: {
        label: 👩🏼‍💻
        style: {
            stroke: transparent
            fill: transparent
            font-size: 100
        }
    }
}