classes: {  
    Miscellaneous-Docker: {
        icon: https://icons.terrastruct.com/dev%2Fdocker.svg
        shape: image
        width: 180
        height: 180
    }
    Miscellaneous-Github: {
        icon: https://icons.terrastruct.com/dev%2Fgithub.svg
        shape: image
        width: 180
        height: 180
    }
    Miscellaneous-User: {
        icon: 'https://icons.terrastruct.com/essentials%2F365-user.svg'
        shape: image
        width: 180
        height: 180
    }
    Miscellaneous-Developer: {
        label: 👩🏼‍💻
        style: {
            stroke: transparent
            fill: transparent
            font-size: 100
        }
    }
    Miscellaneous-Sap: {
        icon: https://icons.terrastruct.com/azure%2FCompute%20Service%20Color%2FSAP%20HANA%20on%20Azure.svg
        shape: image
        width: 350
        height: 350
    }
    Miscellaneous-Elk: {
        icon: https://upload.wikimedia.org/wikipedia/commons/f/f4/Elasticsearch_logo.svg
        shape: image
        width: 350
        height: 350
    }
}