classes: {
    AlreadyExists: {
        style: {
            opacity: 0.5
        }
    }
    Animated: {
        style: {
            animated: true
            font-size: 25
        }
    }
    AWSAccountBox: {
        icon: 'https://icons.terrastruct.com/aws%2F_Group%20Icons%2FAWS-Cloud-alt_light-bg.svg'
        icon.near: top-left
        label.near: top-center
        style: {
            stroke-width: 0
            font-size: 40
            bold: true
            fill: '#FBF5E8'
        }
    }
    DevEnvBox: {
        label.near: top-center
        style: {
            stroke-width: 0
            font-size: 50
            bold: true
            fill: '#E7F2F6'
        }
    }
    QAEnvBox: {
        label.near: top-center
        style: {
            stroke-width: 0
            font-size: 50
            bold: true
            fill: '#F0E8EF'
        }
    }
    ProdEnvBox: {
        label.near: top-center
        style: {
            stroke-width: 0
            font-size: 50
            bold: true
            fill: '#F2DFE1'
        }
    }
    SolutionBox: {
        label.near: top-center
        style: {
            stroke-width: 0
            font-size: 35
            bold: true
            fill: '#F6F7FA'
        }
    }
    FilledBlueBox: {
        style: {
            stroke: '#1D4370' # Holcim blue color
            stroke-dash: 3
            font-size: 25
            fill: '#D9E0E7' # 20% Holcim color, 80% White
        }
    }
    FilledLightBlueBox: {
        style: {
            stroke: '#04BBF1' # Holcim lightblue color
            stroke-dash: 3
            font-size: 25
            fill: '#D5F4FD' # 20% Holcim color, 80% White
        }
    }
    FilledGreenBox: {
        style: {
            stroke: '#94C12E' # Holcim green color
            stroke-dash: 3
            font-size: 25
            fill: '#EDF5DC' # 20% Holcim color, 80% White
        }
    }
    NotAnimated: {
        style: {
            animated: false
            font-size: 25
        }
    }
    Title: {
        style: {
            stroke: '#213178'
            stroke-dash: 3
            font-size: 25
            font-color: '#213178'
        }
    }
    TransparentBlueBox: {
        style: {
            stroke: '#1D4370' # Holcim blue color
            stroke-dash: 3
            font-size: 25
            fill: transparent
        }
    }
    TransparentLightBlueBox: {
        style: {
            stroke: '#04BBF1' # Holcim lightblue color
            stroke-dash: 3
            font-size: 25
            fill: transparent
        }
    }
    TransparentGreenBox: {
        style: {
            stroke: '#94C12E' # Holcim green color
            stroke-dash: 3
            font-size: 25
            fill: transparent
        }
    }
    Note:{
        style: {
            font-size: 16
            bold: false
            fill: transparent
            stroke: transparent 
        }
    }
}
