classes: {
    AlreadyExists: {
        style: {
            opacity: 0.5
        }
    }
    UglyAlreadyExists: {
        style:{
            fill: purple
            opacity: 0.15
            font-color: white
        }
    }
    Animated: {
        style: {
            animated: true
            font-size: 25
        }
    }
    AnimatedSmall: {
        style: {
            animated: true
            font-size: 25
            stroke: '#1D4370'
        }
    }
    AnimatedMedium: {
        style: {
            animated: true
            font-size: 40
            stroke-width: 6
            stroke: '#1D4370'
        }
    }
    AnimatedLarge: {
        style: {
            animated: true
            font-size: 70
            stroke-width: 8
            stroke: '#1D4370'
        }
    }
    AnimatedXLarge: {
        style: {
            animated: true
            font-size: 100
            stroke-width: 12
            stroke: '#1D4370'
        }
    }
    BlueConnection:{
        style: {
            stroke: '#1D4370' # Holcim blue color
        }
    }
    BlueMediumConnection:{
        style: {
            stroke: '#1D4370' # Holcim blue color        
        }
    }
    BlueLargeConnection:{
        style: {
            stroke: '#1D4370' # Holcim blue color
            stroke-width:4
        }
    }
    BlueXLargeConnection:{
        style: {
            stroke: '#1D4370' # Holcim blue color
            stroke-width: 8
        }
    }
    AppBox: {
        label.near: top-center
        style: {
            border-radius: 10
            stroke: '#3B4252'
            stroke-dash: 3
            font-size: 75
            bold: true
            fill: transparent
        }
    }
    DevEnvBox: {
        label.near: top-center
        style: {
            border-radius: 10
            stroke-width: 0
            font-size: 50
            bold: true
            fill: '#E7F2F6'
        }
    }
    QAEnvBox: {
        label.near: top-center
        style: {
            border-radius: 10
            stroke-width: 0
            font-size: 50
            bold: true
            fill: '#F0E8EF'
        }
    }
    ProdEnvBox: {
        label.near: top-center
        style: {
            border-radius: 10
            stroke-width: 0
            font-size: 50
            bold: true
            fill: '#F2DFE1'
        }
    }
    NoResourcesFolderBox: {
        icon: 'https://icons.terrastruct.com/essentials%2F245-folder.svg'
        icon.near: top-left
        label.near: top-center
        style: {
            border-radius: 10
            stroke: '#3B4252'
            stroke-dash: 3
            font-size: 35
            bold: true
            fill: transparent
        }
    }
    SolutionBox: {
        label.near: top-center
        style: {
            border-radius: 10
            stroke-width: 0
            font-size: 35
            bold: true
            fill: '#F6F7FA'
        }
    }
    FilledBlueBox: {
        style: {
            border-radius: 10
            stroke: '#1D4370' # Holcim blue color
            stroke-dash: 3
            font-size: 25
            fill: '#D9E0E7' # 20% Holcim color, 80% White
        }
    }
    FilledLightBlueBox: {
        style: {
            border-radius: 10
            stroke: '#04BBF1' # Holcim lightblue color
            stroke-dash: 3
            font-size: 25
            fill: '#D5F4FD' # 20% Holcim color, 80% White
        }
    }
    FilledGreenBox: {
        style: {
            border-radius: 10
            stroke: '#94C12E' # Holcim green color
            stroke-dash: 3
            font-size: 25
            fill: '#EDF5DC' # 20% Holcim color, 80% White
        }
    }
    NotAnimated: {
        style: {
            animated: false
            font-size: 25
        }
    }
    Title: {
        style: {
            stroke: '#213178'
            stroke-dash: 3
            font-size: 25
            font-color: '#213178'
        }
    }
    InvisibleBox:{
        label:""
        style: {
            stroke: transparent
            fill: transparent
        }
    }
    TransparentBlueBox: {
        style: {
            border-radius: 10
            stroke: '#1D4370' # Holcim blue color
            stroke-dash: 3
            font-size: 25
            fill: transparent
        }
    }
    TransparentLightBlueBox: {
        style: {
            border-radius: 10
            stroke: '#04BBF1' # Holcim lightblue color
            stroke-dash: 3
            font-size: 25
            fill: transparent
        }
    }
    TransparentGreenBox: {
        style: {
            border-radius: 10
            stroke: '#94C12E' # Holcim green color
            stroke-dash: 3
            font-size: 25
            fill: transparent
        }
    }
    SolidLineTransparentBlueBox: {
        style: {
            border-radius: 10
            stroke: '#1D4370' # Holcim blue color
            font-size: 25
            fill: transparent
        }
    }
    SolidLineTransparentLightBlueBox: {
        style: {
            border-radius: 10
            stroke: '#04BBF1' # Holcim lightblue color
            font-size: 25
            fill: transparent
        }
    }
    SolidLineTransparentGreenBox: {
        style: {
            border-radius: 10
            stroke: '#94C12E' # Holcim green color
            font-size: 25
            fill: transparent
        }
    }
    MicroserviceBox:{
        icon: https://s3-us-west-1.amazonaws.com/terrastruct.uploaded-images/1167825004/otpxgfbhsbuweqouvzkltywwzbhzwx.svg
        icon.near: top-left
        label.near: top-center
        style: {
            stroke: '#1D4370' # Holcim blue color
            stroke-width: 1
            font-size: 35
            bold: true
            fill: transparent
        }
    }
    Note: {
        style: {
            font-size: 16
            bold: false
            fill: transparent
            stroke: transparent
        }
    }
}
