...@AWS
...@Miscellaneous

vars: {
    d2-config: {
      theme-id: 104
    }
}
classes: {
  Animated: {
    style: {
      animated: true
    }
  }
  Title: {
    style: {
      stroke: '#213178'
      stroke-dash: 3
      font-size: 25
      font-color: '#213178'
    }
  }
}