classes:{
    AWSAnalytics-KinesisDataStreams:{
        icon: https://icons.terrastruct.com/aws%2FAnalytics%2FAmazon-Kinesis-Data-Streams_light-bg.svg
        shape: image
        width: 180
        height: 180
    }
}