classes: {
    AWSAnalytics-KinesisDataStreams:{
        icon: https://icons.terrastruct.com/aws%2FAnalytics%2FAmazon-Kinesis-Data-Streams_light-bg.svg
        shape: image
        width: 180
        height: 180
    }
    AWSAnalytics-OpenSearch:{
        icon: https://s3-us-west-1.amazonaws.com/terrastruct.uploaded-images/1167825004/urknlclnflcvywidfqncxmcnobvfff.svg
        shape: image
        width: 180
        height: 180
    }
    AWSAnalytics-OpenSearch-Index:{
        icon: https://s3-us-west-1.amazonaws.com/terrastruct.uploaded-images/1167825004/caqafhjrocgqytrduutdgcnalrfwqj.svg
        shape: image
        width: 180
        height: 180
    }
}
