classes: {
    AWSApplicationIntegration-SQS: {
        icon: https://d2-images.holcim.digital/AWS/AplicationIntegration/Amazon-Simple-Queue-Service-SQS_light-bg.svg
        shape: image
        width: 180
        height: 180
    }
    AWSApplicationIntegration-SNS: {
        icon: https://d2-images.holcim.digital/AWS/AplicationIntegration/Amazon-Simple-Notification-Service-SNS_light-bg.svg
        shape: image
        width: 180
        height: 180
    }
    AWSApplicationIntegration-EventBridge: {
        icon: https://d2-images.holcim.digital/AWS/ApplicationIntegration/Amazon-EventBridge_light-bg.svg
        shape: image
        width: 180
        height: 180
    }
    AWSApplicationIntegration-EventBridgeSchedule: {
        icon: https://d2-images.holcim.digital/AWS/AplicationIntegration/AWSApplicationIntegrationEventBridge.svg
        shape: image
        width: 180
        height: 180
    }
    AWSApplicationIntegration-EventBridgeScheduleGroup: {
        icon: https://d2-images.holcim.digital/AWS/AplicationIntegration/AWSApplicationIntegrationEventBridge.svg
        icon.near: top-left
        label.near: outside-top-center
        style: {
            stroke: "#E7157B"
            font-color: "#E7157B"
            fill: transparent
            stroke-width: 1
            stroke-dash: 3
        }
    }
}
