classes: {
    AWSAccountBox: {
        icon: ''
        icon.near: top-left
        label.near: top-center
        style: {
            stroke-width: 0
            font-size: 40
            bold: true
            fill: '#FBF5E8'
        }
    }
}