classes: {
    AWSAccountBox: {
        icon: 'https://icons.terrastruct.com/aws%2F_Group%20Icons%2FAWS-Cloud-alt_light-bg.svg'
        icon.near: top-left
        label.near: top-center
        style: {
            stroke-width: 0
            font-size: 40
            bold: true
            fill: '#FBF5E8'
        }
    }
}