classes: {
    AWSAccountBox: {
        icon: https://d2-images.holcim.digital/AWS/Common/AWS-Cloud-alt_light-bg.svg
        icon.near: top-left
        label.near: top-center
        style: {
            stroke-width: 0
            font-size: 40
            bold: true
            fill: '#FBF5E8'
        }
    }
}