classes: {
    AWSCompute-EC2: {
        icon: https://icons.terrastruct.com/aws%2FCompute%2F_Instance%2FAmazon-EC2_C4-Instance_light-bg.svg
        shape: image
        width: 180
        height: 180
    }
    AWSCompute-Lambda: {
        icon: https://icons.terrastruct.com/aws%2FCompute%2FAWS-Lambda_light-bg.svg
        shape: image
        width: 180
        height: 180
    }
}
