classes: {
    AWSCompute-EC2: {
        icon: https://d2-images.holcim.digital/AWS/Compute/Amazon-EC2_C4-Instance_light-bg.svg
        shape: image
        width: 180
        height: 180
    }
    AWSCompute-Lambda: {
        icon: https://d2-images.holcim.digital/AWS/Compute/AWS-Lambda_light-bg.svg
        shape: image
        width: 180
        height: 180
    }
    AWSCompute-LambdaAlias: {
        icon: https://d2-images.holcim.digital/AWS/Compute/AWS-Lambda_Lambda-Function_light-bg.svg
        shape: image
        width: 180
        height: 180
    }
}
