classes: {
  AWSContainers-ECR: {
    icon: https://icons.terrastruct.com/aws%2FCompute%2FAmazon-EC2-Container-Registry.svg
    shape: image
    width: 180
    height: 180
  }
  AWSContainers-ECS-TaskDefinition: {
    icon: https://icons.d2lang.com/aws%2FCompute%2FAmazon-Elastic-Container-Service_Task_light-bg.svg
    shape: image
    width: 180
    height: 180
  }
  AWSContainers-ECS: {
    icon: https://icons.terrastruct.com/aws%2FCompute%2FAmazon-Elastic-Container-Service.svg
    shape: image
    width: 180
    height: 180
  }
  AWSContainers-Fargate: {
    icon: https://icons.terrastruct.com/aws%2FCompute%2FAWS-Fargate.svg
    shape: image
    width: 180
    height: 180
  }
}
