classes: {
    AWSDatabase-RDS: {
        icon: https://icons.terrastruct.com/aws%2FDatabase%2FAmazon-RDS_Amazon-RDS_instance_light-bg.svg
        shape: image
        width: 180
        height: 180
    }
    AWSDatabase-DynamoDB: {
        icon: https://icons.terrastruct.com/aws%2FDatabase%2FAmazon-DynamoDB_light-bg.svg
        shape: image
        width: 180
        height: 180
    }
}
