classes: {
    AWSDatabase-RDS: {
        icon: https://icons.terrastruct.com/aws%2FDatabase%2FAmazon-RDS_Amazon-RDS_instance_light-bg.svg
        shape: image
        width: 180
        height: 180
    }
    AWSDatabase-DynamoDB: {
        icon: https://icons.terrastruct.com/aws%2FDatabase%2FAmazon-DynamoDB_light-bg.svg
        shape: image
        width: 180
        height: 180
    }
    AWSDatabase-SubnetGroup: {
        icon: https://icons.terrastruct.com/aws%2F_Group%20Icons%2FVPC-subnet-private_light-bg.svg
        icon.near: top-left
        style: {
            stroke: transparent
            font-color: black
            fill: '#DFEFF7'
        }
    }
    AWSDatabase-ParameterGroup: {
        icon: https://icons.terrastruct.com/essentials%2F257-file.svg
        shape: image
        width: 80
        height: 80
    }
    AWSDatabase-OptionGroup: {
        icon: https://icons.terrastruct.com/essentials%2F257-file.svg
        shape: image
        width: 80
        height: 80
    }

}
