classes: {
    AWSDatabase-RDS: {
        icon: https://d2-images.holcim.digital/AWS/Database/Amazon-RDS_light-bg.svg
        shape: image
        width: 180
        height: 180
    }
    AWSDatabase-Aurora: {
        icon: https://d2-images.holcim.digital/AWS/Database/Amazon-Aurora_light-bg.svg
        shape: image
        width: 180
        height: 180
    }
    AWSDatabase-DynamoDB: {
        icon: https://d2-images.holcim.digital/AWS/Database/Amazon-DynamoDB_light-bg.svg
        shape: image
        width: 180
        height: 180
    }
    AWSDatabase-SubnetGroup: {
        icon: https://d2-images.holcim.digital/AWS/Database/VPC-subnet-private_light-bg.svg
        icon.near: top-left
        label.near: top-center
        style: {
            stroke: transparent
            font-color: black
            fill: '#DFEFF7'
        }
    }
    AWSDatabase-ParameterGroup: {
        icon: https://d2-images.holcim.digital/AWS/Database/otaatcbrlcingltbwaadrxskmzqyqk.png
        shape: image
        width: 80
        height: 80
    }
    AWSDatabase-OptionGroup: {
        icon: https://d2-images.holcim.digital/AWS/Database/vpwmjkiqoxhrktgmvwiiytgbpfeodf.png
        shape: image
        width: 80
        height: 80
    }
    AWSDatabase-Cluster: {
        icon: https://d2-images.holcim.digital/AWS/Database/Database.svg
        icon.near: top-left
        label.near: top-center
        style: {
            stroke: transparent
            font-color: black
            fill: '#DFEFF7'
        }
    }
}
