classes:{
    AWSMachineLearning-Bedrock:{
        icon: https://s3-us-west-1.amazonaws.com/terrastruct.uploaded-images/1167825004/gmreqtjgtluvdywuapsuqhfmiziqdv.svg
        label: "Amazon Bedrock"
        shape: image
        width: 180
        height: 180
    }
}
