classes:{
    AWSMachineLearning-Bedrock:{
        icon: https://s3-us-west-1.amazonaws.com/terrastruct.uploaded-images/1167825004/gmreqtjgtluvdywuapsuqhfmiziqdv.svg
        label: "Amazon Bedrock"
        shape: image
        width: 180
        height: 180
    }
    AWSMachineLearning-Bedrock-DataSource:{
        icon: https://s3-us-west-1.amazonaws.com/terrastruct.uploaded-images/1167825004/kseeyixfyqkuuruwzqoytmkeyrkxam.svg
        label: "Amazon Bedrock"
        shape: image
        width: 100
        height: 100
    }
}
