classes: {
    AWSManagementGovernance-Organization: {
        icon: https://icons.terrastruct.com/aws%2FManagement%20&%20Governance%2FAWS-Organizations_light-bg.svg
        icon.near: top-left
        label.near: top-center
        style.fill: transparent
        style.bold: true
        style.font-size: 64
        style.stroke: '#C82636'
        style.stroke-width: 8
        style.border-radius: 3
    }
    AWSManagementGovernance-OU: {
        icon: https://icons.terrastruct.com/aws%2FManagement%20&%20Governance%2FAWS-Organizations_Organizational-unit_light-bg.svg
        icon.near: top-left
        label.near: top-center
        style.fill: transparent
        style.bold: true
        style.stroke-width: 2
        style.stroke-dash: 3
        style.stroke: '#C82636'
    }
    AWSManagementGovernance-Account: {
        icon: https://icons.terrastruct.com/aws%2FManagement%20&%20Governance%2FAWS-Organizations_Account_light-bg.svg
        shape: image
        width: 180
        height:180
    }
    AWSSecurityIdentity-SCP: {
        icon: https://icons.terrastruct.com/aws%2FSecurity%2C%20Identity%2C%20&%20Compliance%2FAWS-Identity-and-Access-Management-IAM_Permissions_light-bg.svg
        shape: image
        style.font-color: '#C82636'
        width: 50
        height: 50
    }
}