classes: {
    AWSNetworking-VPC: {
        icon: https://d2-images.holcim.digital/AWS/Networking/Virtual-private-cloud-VPC_light-bg.svg
        style: {
            stroke: green
            font-color: green
            fill: white
        }
    }
    AWSNetworking-PrivateSubnet:{
        icon: https://d2-images.holcim.digital/AWS/Networking/VPC-subnet-private_light-bg.svg
        icon.near: top-left
        style: {
            stroke: cornflowerblue
            font-color: cornflowerblue
            fill: transparent
        }
    }
    AWSNetworking-PublicSubnet:{
        icon: https://d2-images.holcim.digital/AWS/Networking/VPC-subnet-public_light-bg.svg
        icon.near: top-left
        style: {
            stroke: green
            font-color: green
            fill: transparent
        }
    }
    AWSNetworking-SecurityGroup:{
        label.near: outside-top-center
        style: {
            stroke: red
            font-color: red
            fill: transparent
            stroke-width: 1
        }
    }
    AWSNetworking-SecurityGroupIcon:{
        icon: https://d2-images.holcim.digital/AWS/Networking/xdxkhvxdlsucosibhelkzrbnehzbha.svg
        shape: image
        width: 180
        height: 180
    }
    AWSNetworking-InternetGateway: {
        icon: https://d2-images.holcim.digital/AWS/Networking/Amazon-VPC_Internet-Gateway_light-bg.svg
        style: {
            stroke: transparent
            font-color: black
            fill: transparent
        }
    } 
    AWSNetworking-CloudFront: {
        icon: https://d2-images.holcim.digital/AWS/Networking/Amazon-CloudFront_light-bg.svg
        shape: image
        width: 180
        height: 180
    }
    AWSNetworking-Route53: {
        icon: https://d2-images.holcim.digital/AWS/Networking/Amazon-Route-53_light-bg.svg
        shape: image
        width: 180
        height: 180
    }
    AWSNetworking-ApiGateway: {
        icon: https://d2-images.holcim.digital/AWS/Networking/Amazon-API-Gateway_light-bg.svg
        shape: image
        width: 180
        height: 180
    }
    AWSNetworking-ApiGatewayDomainName: {
        icon: https://d2-images.holcim.digital/AWS/Networking/Amazon-API-Gateway_Endpoint_light-bg.svg
        shape: image
        width: 180
        height: 180
    }
    AWSNetworking-ApplicationLoadBalancer: {
        icon: https://d2-images.holcim.digital/AWS/Networking/Elastic-Load-Balancing-ELB_Application-load-balancer_light-bg.svg
        width: 180
        height: 180
    }
    AWSNetworking-VPCEndpoint: {
        icon: https://d2-images.holcim.digital/AWS/Networking/Amazon-VPC_Endpoints_light-bg.svg
        shape: image
        width: 180
        height: 180
    }
    AWSNetworking-TransitGateway: {
        icon: https://d2-images.holcim.digital/AWS/Networking/AWS-Transit-Gateway.svg
        shape: image
        width: 180
        height: 180
    }
    
}
