classes: {
    AWSNetworking-VPC: {
        icon: https://icons.terrastruct.com/aws%2F_Group%20Icons%2FVirtual-private-cloud-VPC_light-bg.svg
        style: {
            stroke: green
            font-color: green
            fill: white
        }
    }
    AWSNetworking-PrivateSubnet:{
        icon: https://icons.terrastruct.com/aws%2F_Group%20Icons%2FVPC-subnet-private_light-bg.svg
        icon.near: top-left
        style: {
            stroke: cornflowerblue
            font-color: cornflowerblue
            fill: transparent
        }
    }
    AWSNetworking-PublicSubnet:{
        icon: https://icons.terrastruct.com/aws%2F_Group%20Icons%2FVPC-subnet-public_light-bg.svg
        icon.near: top-left
        style: {
            stroke: green
            font-color: green
            fill: transparent
        }
    }
    AWSNetworking-InternetGateway: {
        icon: https://icons.terrastruct.com/aws%2FNetworking%20&%20Content%20Delivery%2FAmazon-VPC_Internet-Gateway_light-bg.svg
        style: {
            stroke: transparent
            font-color: black
            fill: transparent
        }
    } 
    AWSNetworking-CloudFront: {
        icon: https://icons.terrastruct.com/aws%2FNetworking%20&%20Content%20Delivery%2FAmazon-CloudFront_light-bg.svg
        shape: image
        width: 180
        height: 180
    }
    AWSNetworking-Route53: {
        icon: https://icons.terrastruct.com/aws%2FNetworking%20&%20Content%20Delivery%2FAmazon-Route-53_light-bg.svg
        shape: image
        width: 180
        height: 180
    }
    AWSNetworking-ApiGateway: {
        icon: https://icons.terrastruct.com/aws%2FNetworking%20&%20Content%20Delivery%2FAmazon-API-Gateway_light-bg.svg
        shape: image
        width: 180
        height: 180
    }
    AWSNetworking-ApplicationLoadBalancer: {
        icon: https://icons.terrastruct.com/aws%2FNetworking%20&%20Content%20Delivery%2FElastic-Load-Balancing-ELB_Application-load-balancer_light-bg.svg
        shape: image
        width: 180
        height: 180
    }
    AWSNetworking-VPCEndpoint: {
        icon:https://icons.terrastruct.com/aws%2FNetworking%20&%20Content%20Delivery%2FAmazon-VPC_Endpoints_light-bg.svg
        shape: image
        width: 180
        height: 180
    }
    AWSNetworking-TransitGateway: {
        icon: https://icons.terrastruct.com/aws%2FNetworking%20&%20Content%20Delivery%2FAWS-Transit-Gateway.svg
        shape: image
        width: 180
        height: 180
    }
    
}
