classes: {
    AWSSecurityIdentity-ACMCertificate: {
        icon: https://icons.terrastruct.com/aws%2FSecurity%2C%20Identity%2C%20&%20Compliance%2FAWS-Certificate-Manager_light-bg.svg
        shape: image
        width: 180
        height: 180
    }
    AWSSecurityIdentity-IAMUser: {
        icon: https://global-uploads.webflow.com/5f05d5858fab461d0d08eaeb/635155d9063787953314667c_iam_user_light.svg
        shape: image
        width: 180
        height: 180
    }
    AWSSecurityIdentity-IAMRole: {
        icon: https://icons.terrastruct.com/aws%2FSecurity%2C%20Identity%2C%20&%20Compliance%2FAWS-Identity-and-Access-Management-IAM_Role_light-bg.svg
        shape: image
        width: 180
        height: 180
    }
    AWSSecurityIdentity-IAMGroup: {
        icon: https://icons.terrastruct.com/aws%2F_General%2FUsers_light-bg.svg
        shape: image
        width: 180
        height: 180
    }
    AWSSecurityIdentity-IAMPolicy: {
        icon: https://icons.terrastruct.com/aws%2FSecurity%2C%20Identity%2C%20&%20Compliance%2FAWS-Identity-and-Access-Management-IAM_Permissions_light-bg.svg
        shape: image
        width: 100
        height: 100
    }
    AWSSecurityIdentity-KMSKey: {
        icon: https://icons.terrastruct.com/aws%2FSecurity%2C%20Identity%2C%20&%20Compliance%2FAWS-Key-Management-Service_light-bg.svg
        shape: image
        width: 180
        height: 180
    }
    AWSSecurityIdentity-AccessKey: {
        icon: https://icons.terrastruct.com/aws%2FSecurity%2C%20Identity%2C%20&%20Compliance%2FAWS-Identity-and-Access-Management-IAM_Long-term-Security-Credential_light-bg.svg
        shape: image
        width: 180
        height: 180
    }
    AWSSecurityIdentity-SecretManager: {
        icon: https://icons.terrastruct.com/aws%2FSecurity%2C%20Identity%2C%20&%20Compliance%2FAWS-Secrets-Manager_light-bg.svg
        shape: image
        width: 180
        height: 180
    }
    AWSSecurityIdentity-Cognito: {
        icon: https://icons.terrastruct.com/aws%2FSecurity%2C%20Identity%2C%20&%20Compliance%2FAmazon-Cognito_light-bg.svg
        shape: image
        width: 180
        height: 180
    }
    AWSSecurityIdentity-CognitoAppClient: {
        icon: https://s3-us-west-1.amazonaws.com/terrastruct.uploaded-images/1167825004/naqnvvdwmvgfzuquvcvktzduglpbgl.svg
        shape: image
        width: 180
        height: 180
    }
}
