classes: {
    AWSStorage-S3: {
        icon: https://d2-images.holcim.digital/AWS/Storage/Amazon-Simple-Storage-Service-S3.svg
        shape: image
        width: 180
        height: 180
    }
    AWSStorage-S3Lifecycle: {
        icon: https://d2-images.holcim.digital/AWS/Storage/033-repeat.svg 
        shape: image
        width: 50
        height: 50
    }
    AWSStorage-S3Object: {
        icon: https://d2-images.holcim.digital/AWS/Storage/Amazon-Simple-Storage-Service-S3_Bucket-with-Objects_light-bg.svg  
        shape: image
        width: 180
        height: 180
    }
}
