classes: {
    AWSStorage-S3: {
        icon: https://icons.terrastruct.com/aws%2FStorage%2FAmazon-Simple-Storage-Service-S3.svg     
        shape: image
        width: 180
        height: 180
    }
    AWSStorage-S3Lifecycle: {
        icon: https://icons.terrastruct.com/essentials%2F033-repeat.svg     
        shape: image
        width: 50
        height: 50
    }
}
