classes: {
    Holcim-Zonda:{
        icon: https://s3-us-west-1.amazonaws.com/terrastruct.uploaded-images/1167825004/uqmhirhhhzctdbzxsnjzidyyhpbcrr.svg
        label: ""
        shape: image
        width: 280
        height: 280
    }
    Holcim-MyTruck:{
        icon: https://s3-us-west-1.amazonaws.com/terrastruct.uploaded-images/1167825004/ncsrgwuznjrcrfnkzzxpklsymobsgk.png
        label: "MyTruck"
        shape: image
        width: 280
        height: 280
    }
}
