classes: {
    Holcim-Zonda:{
        icon: https://d2-images.holcim.digital/Miscellaneus/Holcim/HolcimZonda.svg
        label: ""
        shape: image
        width: 280
        height: 280
    }
    Holcim-MyTruck:{
        icon: https://d2-images.holcim.digital/Miscellaneus/Holcim/HolcimMyTruck.svg
        label: "MyTruck"
        shape: image
        width: 280
        height: 280
    }
}
