classes: {  
    Miscellaneous-Docker: {
        icon: https://d2-images.holcim.digital/Miscellaneus/Miscellaneus/docker.svg
        shape: image
        width: 180
        height: 180
    }
    Miscellaneous-GitHub: {
        icon: https://d2-images.holcim.digital/Miscellaneus/Miscellaneus/github.svg
        shape: image
        width: 180
        height: 180
    }
    Miscellaneous-User: {
        icon: https://d2-images.holcim.digital/Miscellaneus/Miscellaneus/MiscellaneusUser.svg
        shape: image
        width: 180
        height: 180
    }
    Miscellaneous-Developer: {
        icon: https://d2-images.holcim.digital/Miscellaneus/Miscellaneus/MiscellaneusDeveloper.png
        shape: image
        width: 180
        height: 180
    }
    Miscellaneous-Sap: {
        icon: https://d2-images.holcim.digital/Miscellaneus/Miscellaneus/SAPHANAonAzure.svg
        shape: image
        width: 350
        height: 350
    }
    Miscellaneous-Elk: {
        icon: https://d2-images.holcim.digital/Miscellaneus/Miscellaneus/Elasticsearch_logo.svg
        shape: image
        width: 350
        height: 350
    }
    Miscellaneous-ElasticSearch: {
        icon: https://d2-images.holcim.digital/Miscellaneus/Miscellaneus/MiscellaneusElasticSearch.svg
        shape: image
        width: 180
        height: 180
    }
    Miscellaneous-ROSA: {
        icon: https://d2-images.holcim.digital/Miscellaneus/Miscellaneus/OpenShift-LogoType.svg.png
        shape: image
        width: 180
        height: 180
    }
    Miscellaneous-RH: {
        icon: https://d2-images.holcim.digital/Miscellaneus/Miscellaneus/Red_Hat_logo.svg
        shape: image
        width: 180
        height: 180
    }
    Miscellaneous-Internet: {
        icon: https://d2-images.holcim.digital/Miscellaneus/Miscellaneus/140-internet.svg
        shape: image
        width: 180
        height: 180
    }
    Miscellaneous-Jenkins: {
        icon: https://d2-images.holcim.digital/Miscellaneus/Miscellaneus/MiscellaneusJenkins.svg
        shape: image
        width: 180
        height: 180
    }
    Miscellaneous-Quay: {
        icon: https://d2-images.holcim.digital/Miscellaneus/Miscellaneus/MiscellaneusQuay.svg
        shape: image
        width: 240
        height: 130
    }
    Miscellaneous-TomTom:{
        icon: https://d2-images.holcim.digital/Miscellaneus/Miscellaneus/MiscellaneusTomTom.svg
        label: ""
        shape: image
        width: 360
        height: 360
    }
    Miscellaneous-MixTelematics:{
        icon: https://d2-images.holcim.digital/Miscellaneus/Miscellaneus/MiscellaneusMixTelematics.svg
        label: ""
        shape: image
        width: 280
        height: 280
    }
    Miscellaneous-Nifi:{
        icon: https://d2-images.holcim.digital/Miscellaneus/Miscellaneus/MiscellaneusNifi.svg
        label: ""
        shape: image
        width: 280
        height: 280
    }
    Miscellaneous-Imperva:{
        icon: https://d2-images.holcim.digital/Miscellaneus/Miscellaneus/MiscellaneusImperva.svg
        label: ""
        shape: image
        width: 280
        height: 280
    }
    Miscellaneous-Site:{
        icon: https://d2-images.holcim.digital/Miscellaneus/Miscellaneus/MiscellaneusSite.svg
        label: ""
        shape: image
        width: 180
        height: 180
    }
    Miscellaneous-Progps:{
        icon: https://d2-images.holcim.digital/Miscellaneus/Miscellaneus/MiscellaneusProgps.svg
        label: ""
        shape: image
        width: 180
        height: 180
    }
    Miscellaneous-Algeofleet:{
        icon: https://d2-images.holcim.digital/Miscellaneus/Miscellaneus/MiscellaneusAlgeofleet.svg
        label: ""
        shape: image
        width: 180
        height: 180
    }
    Miscellaneous-Idenet:{
        icon: https://d2-images.holcim.digital/Miscellaneus/Miscellaneus/MiscellaneusIdenet.svg
        label: ""
        shape: image
        width: 180
        height: 180
    }
    Miscellaneous-EgyptScraper:{
        icon: https://d2-images.holcim.digital/Miscellaneus/Miscellaneus/MiscellaneusEgyptScraper.svg
        label: ""
        shape: image
        width: 180
        height: 180
    }
    Miscellaneous-Filter:{
        label: "Pattern filter"
        icon: https://d2-images.holcim.digital/Miscellaneus/Miscellaneus/215-funnel.svg
        shape: image
    }
    Miscellaneous-Nanolike:{
        label: "Nanolike"
        icon: https://d2-images.holcim.digital/Miscellaneus/Miscellaneus/MiscellaneusNanolike.svg
        shape: image
        width: 180
        height: 180
    }
    Miscellaneous-Salesforce:{
        label: "Salesforce"
        icon: https://d2-images.holcim.digital/Miscellaneus/Miscellaneus/MiscellaneusSalesforce.svg
        shape: image
        width: 180
        height: 180
    }
    Miscellaneous-Whatsapp:{
        label: ""
        icon: https://d2-images.holcim.digital/Miscellaneus/Miscellaneus/MiscellaneusWhatsapp.svg
        shape: image
        width: 280
        height: 280
    }
    Miscellaneous-Mulesoft:{
        label: ""
        icon: https://d2-images.holcim.digital/Miscellaneus/Miscellaneus/MiscellaneusMulesoft.svg
        shape: image
        width: 180
        height: 180
    }
    Miscellaneous-Target:{
        label: ""
        icon: https://d2-images.holcim.digital/Miscellaneus/Miscellaneus/142-target.svg
        shape: image
        width: 180
        height: 180
    }
    Miscellaneous-Genesys:{
        label: ""
        icon: https://d2-images.holcim.digital/Miscellaneus/Miscellaneus/Miscellaneus-Genesys.svg
        shape: image
        width: 280
        height: 280
    }
}
