classes: {  
    Miscellaneous-Docker: {
        icon: https://icons.terrastruct.com/dev%2Fdocker.svg
        shape: image
        width: 180
        height: 180
    }
    Miscellaneous-GitHub: {
        icon: https://icons.terrastruct.com/dev%2Fgithub.svg
        shape: image
        width: 180
        height: 180
    }
    Miscellaneous-User: {
        icon: 'https://s3-us-west-1.amazonaws.com/terrastruct.uploaded-images/1167825004/ipamgtdxgxbyzwsfaaghvuiekflvqn.svg'
        shape: image
        width: 180
        height: 180
        style.font-size: 70
        style.font-color: "#474747"
        label.near: outside-bottom-center
    }
    Miscellaneous-Developer: {
        icon: 'https://s3-us-west-1.amazonaws.com/terrastruct.uploaded-images/1167825004/laolsguksuweshwkgjpxcewvsjiasd.png'
        shape: image
        width: 180
        height: 180
    }
    Miscellaneous-Sap: {
        icon: https://icons.terrastruct.com/azure%2FCompute%20Service%20Color%2FSAP%20HANA%20on%20Azure.svg
        shape: image
        width: 350
        height: 350
    }
    Miscellaneous-Elk: {
        icon: https://upload.wikimedia.org/wikipedia/commons/f/f4/Elasticsearch_logo.svg
        shape: image
        width: 350
        height: 350
    }
    Miscellaneous-ElasticSearch: {
        icon: https://s3-us-west-1.amazonaws.com/terrastruct.uploaded-images/1167825004/svhwjraqittqglmapnqkruuzpubbyb.svg
        shape: image
        width: 180
        height: 180
    }
    Miscellaneous-ROSA: {
        icon: https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/OpenShift-LogoType.svg/1917px-OpenShift-LogoType.svg.png
        shape: image
        width: 180
        height: 180
    }
    Miscellaneous-RH: {
        icon: https://upload.wikimedia.org/wikipedia/commons/d/d8/Red_Hat_logo.svg
        shape: image
        width: 180
        height: 180
    }
    Miscellaneous-Internet: {
        icon: https://icons.terrastruct.com/essentials%2F140-internet.svg
        shape: image
        width: 180
        height: 180
    }
    Miscellaneous-Jenkins: {
        icon: https://s3-us-west-1.amazonaws.com/terrastruct.uploaded-images/1167825004/ypboavlhwdjclsdieghxjwhajyhmdm.svg
        shape: image
        width: 180
        height: 180
    }
    Miscellaneous-Quay: {
        icon: https://s3-us-west-1.amazonaws.com/terrastruct.uploaded-images/1167825004/eezkoejgcctplshmepqxnewcppduft.svg
        shape: image
        width: 240
        height: 130
    }
    Miscellaneous-TomTom:{
        icon: https://s3-us-west-1.amazonaws.com/terrastruct.uploaded-images/1167825004/rtzctnoitbyiuclhcryaaomuffqmam.svg
        label: ""
        shape: image
        width: 360
        height: 360
    }
    Miscellaneous-MixTelematics:{
        icon: https://s3-us-west-1.amazonaws.com/terrastruct.uploaded-images/1167825004/mawwvtowjxtsdqptzftfoemfzjrohz.svg
        label: ""
        shape: image
        width: 280
        height: 280
    }
    Miscellaneous-Nifi:{
        icon: https://s3-us-west-1.amazonaws.com/terrastruct.uploaded-images/1167825004/hsrjxtjqftyxfrtslolmbbjwdgmgya.svg
        label: ""
        shape: image
        width: 280
        height: 280
    }
    Miscellaneous-Imperva:{
        icon: https://s3-us-west-1.amazonaws.com/terrastruct.uploaded-images/1167825004/mkpdldbpnkeooywfijrextoxosjpah.svg
        label: ""
        shape: image
        width: 280
        height: 280
    }
    Miscellaneous-Site:{
        icon: https://s3-us-west-1.amazonaws.com/terrastruct.uploaded-images/1167825004/agcnhwcswozhqsoygzmxvsucxvdaxz.svg
        label: ""
        shape: image
        width: 180
        height: 180
    }
    Miscellaneous-Progps:{
        icon: https://s3-us-west-1.amazonaws.com/terrastruct.uploaded-images/1167825004/mwljgyulnoorsbchixytvqkwkgohzn.svg
        label: ""
        shape: image
        width: 180
        height: 180
    }
    Miscellaneous-Algeofleet:{
        icon: https://s3-us-west-1.amazonaws.com/terrastruct.uploaded-images/1167825004/dfmvvmixucwyqnozsjfdgweditzxon.svg
        label: ""
        shape: image
        width: 180
        height: 180
    }
    Miscellaneous-Idenet:{
        icon: https://s3-us-west-1.amazonaws.com/terrastruct.uploaded-images/1167825004/pofyynduzzlpxfgywexnbrojlqvkoy.svg
        label: ""
        shape: image
        width: 180
        height: 180
    }
    Miscellaneous-EgyptScraper:{
        icon: https://s3-us-west-1.amazonaws.com/terrastruct.uploaded-images/1167825004/thwsostijxoreijldnjbrvvnhqxges.svg
        label: ""
        shape: image
        width: 180
        height: 180
    }
}
