classes: {
    GCP-AuthPlatform: {
        icon: https://icons.terrastruct.com/gcp%2FProducts%20and%20services%2FSecurity%2FCloud%20Resource%20Manager.svg
        shape: image
        width: 180
        height: 180
    }
}
