classes:{
    Languages-nodejs:{
        icon: https://d2-images.holcim.digital/Technologies/Languages/nodejs.svg
        icon.near: top-left
        label:""
        style: {
            fill: transparent
            stroke-width: 1
            stroke-dash: 3
        }
    }
    Languages-java:{
        icon: https://d2-images.holcim.digital/Technologies/Languages/java.svg
        icon.near: top-left
        label:""
        style: {
            fill: transparent
            stroke-width: 1
            stroke-dash: 3
        }
    }
    Languages-python:{
        icon: https://d2-images.holcim.digital/Technologies/Languages/python.svg
        icon.near: top-left
        label:""
        style: {
            fill: transparent
            stroke-width: 1
            stroke-dash: 3
        }
    }
    Languages-dotnet:{
        icon: https://d2-images.holcim.digital/Technologies/Languages/dotnet.svg
        icon.near: top-left
        label:""
        style: {
            fill: transparent
            stroke-width: 1
            stroke-dash: 3
        }
    }
    Languages-php:{
        icon: https://d2-images.holcim.digital/Technologies/Languages/php.svg
        icon.near: top-left
        label:""
        style: {
            fill: transparent
            stroke-width: 1
            stroke-dash: 3
        }
    }
    Languages-generic:{
        icon: https://d2-images.holcim.digital/Technologies/Languages/generic.svg
        icon.near: top-left
        label:""
        style: {
            fill: transparent
            stroke-width: 1
            stroke-dash: 3
        }
    }
}