classes:{
    Languages-nodejs:{
        icon: https://s3-us-west-1.amazonaws.com/terrastruct.uploaded-images/1167825004/ucpkwomawrzzdrwrnnkingsgxmvshd.svg
        icon.near: top-left
        label:""
        style: {
            fill: transparent
            stroke-width: 1
            stroke-dash: 3
        }
    }
    Languages-java:{
        icon: https://icons.terrastruct.com/dev%2Fjava.svg
        icon.near: top-left
        label:""
        style: {
            fill: transparent
            stroke-width: 1
            stroke-dash: 3
        }
    }
    Languages-python:{
        icon: https://icons.terrastruct.com/dev%2Fpython.svg
        icon.near: top-left
        label:""
        style: {
            fill: transparent
            stroke-width: 1
            stroke-dash: 3
        }
    }
    Languages-dotnet:{
        icon: https://s3-us-west-1.amazonaws.com/terrastruct.uploaded-images/1167825004/sopynqvrhddzvdtwhwofljwcjgwjhk.svg
        icon.near: top-left
        label:""
        style: {
            fill: transparent
            stroke-width: 1
            stroke-dash: 3
        }
    }
    Languages-php:{
        icon: https://icons.terrastruct.com/dev%2Fphp.svg
        icon.near: top-left
        label:""
        style: {
            fill: transparent
            stroke-width: 1
            stroke-dash: 3
        }
    }
    Languages-generic:{
        icon: https://s3-us-west-1.amazonaws.com/terrastruct.uploaded-images/1167825004/efhhdyccnwwsvfoqjyitmiqjkntgij.svg
        icon.near: top-left
        label:""
        style: {
            fill: transparent
            stroke-width: 1
            stroke-dash: 3
        }
    }
}