classes: {  
    OpenShift-Pod: {
        icon: https://s3-us-west-1.amazonaws.com/terrastruct.uploaded-images/1167825004/cqsxkmepbolriwlwqqcmjvofkglgrt.svg
        shape: image
        label.near: outside-bottom-center
        width: 180
        height: 180
    }
    OpenShift-Route: {
        icon: https://s3-us-west-1.amazonaws.com/terrastruct.uploaded-images/1167825004/zvfxejfnjoaykavzmeqqymrggayryc.svg
        shape: image
        label.near: outside-bottom-center
        width: 180
        height: 180
    }
    OpenShift-Box: {
        icon: https://s3-us-west-1.amazonaws.com/terrastruct.uploaded-images/1167825004/frgpokeadagbgkjptjflixrsgveiyd.svg
        icon.near: top-left
        label.near: top-center
        style: {
            stroke-width: 0
            font-size: 40
            bold: true
            fill: '#FFE6E6' #OpenShift Red at 5% opacity
        }

    }
}