classes: { 
    OpenShift: {
        icon: https://d2-images.holcim.digital/Technologies/OpenShift/OpenShift.svg
        shape: image
        label.near: outside-bottom-center
        width: 180
        height: 180
    }
    OpenShift-Pod: {
        icon: https://d2-images.holcim.digital/Technologies/OpenShift/OpenShiftPod.svg
        shape: image
        label.near: outside-bottom-center
        width: 180
        height: 180
    }
    OpenShift-Route: {
        icon: https://d2-images.holcim.digital/Technologies/OpenShift/OpenShiftRoute.svg
        shape: image
        label.near: outside-bottom-center
        width: 180
        height: 180
    }
    OpenShift-Box: {
        icon: https://d2-images.holcim.digital/Technologies/OpenShift/OpenShift.svg
        icon.near: top-left
        label.near: top-center
        style: {
            stroke-width: 0
            font-size: 40
            bold: true
            fill: '#FFE6E6' #OpenShift Red at 5% opacity
        }

    }
}
